spring.application.name=Pokeopedia
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/pokepedia}
spring.datasource.username=root
spring.datasource.password=Stormer.09

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

api.security.token.secret = ${JWT_SECRET:secret}
